"""Sector configuration for user profiles."""

SECTORS = {
    "government": "Government/ Public Sector",
    "donor": "Philanthropic Organization",
    "local_ngo": "Local NGO (national or subnational)",
    "international_ngo": "International NGO",
    "un_international": "Intergovernmental / Multilateral Organization",
    "academic": "Academic / Research Organization",
    "journalist": "Journalist / Media Organization",
    "indigenous": "Indigenous of Community-Based Organization",
    "private_sector": "Private Sector / Business",
    "individual": "Individual / No Affiliation",
    "other": "Other",
}

# Mapping of sectors to their available roles
SECTOR_ROLES = {
    "government": {
        "forest_management": "Forest Management/Park Management",
        "law_enforcement": "Law Enforcement",
        "legislature": "Legislature/Parliament",
        "ministry_agency": "Ministry/National Agency",
        "subnational_agency": "Subnational Agency",
        "donor_agency": "Donor Agency",
        "other": "Other:",
    },
    "donor": {
        "director_executive": "Director/Executive",
        "project_manager": "Project/Program Manager",
        "researcher": "Researcher",
        "monitoring_evaluation": "Monitoring/Evaluation",
        "field_staff": "Field/Country Staff",
        "other": "Other:",
    },
    "local_ngo": {
        "director_executive": "Director/Executive",
        "project_manager": "Project/Program Manager",
        "monitoring_evaluation": "Monitoring/Evaluation Specialist",
        "gis_technical": "GIS/Technical Specialist",
        "researcher": "Researcher",
        "field_staff": "Field Staff/ Country Staff",
        "communications": "Communications Specialist",
        "other": "Other:",
    },
    "international_ngo": {
        "director_executive": "Director/Executive",
        "project_manager": "Project/Program Manager",
        "monitoring_evaluation": "Monitoring/Evaluation Specialist",
        "gis_technical": "GIS/Technical Specialist",
        "field_staff": "Field/Country Staff",
        "communications": "Communications Specialist",
        "researcher": "Researcher",
        "other": "Other:",
    },
    "un_international": {
        "director_executive": "Director/Executive",
        "project_manager": "Project/Program Manager",
        "researcher": "Researcher",
        "field_staff": "Field/Country Staff",
        "monitoring_evaluation": "Monitoring/Evaluation Specialist",
        "gis_technical": "GIS/Technical Specialist",
        "communications": "Communications Specialist",
        "other": "Other:",
    },
    "academic": {
        "faculty_primary": "Faculty (Primary/Secondary)",
        "faculty_university": "Faculty (University)",
        "student_primary": "Student (Primary/Secondary)",
        "student_university": "Student (University/Graduate)",
        "researcher_postdoc": "Researcher (Post-Doc, Fellow, etc.)",
        "other": "Other:",
    },
    "journalist": {
        "reporter": "Reporter",
        "editor": "Editor",
        "other": "Other:",
    },
    "indigenous": {
        "community_leader": "Community Leader",
        "forest_manager": "Forest Manager/Monitor",
        "gis_technical": "GIS/Technical Specialist",
        "communications": "Communications Specialist",
        "other": "Other:",
    },
    "private_sector": {
        "director_executive": "Director / Executive",
        "sustainability_esg": "Sustainability / ESG Manager",
        "supply_chain_manager": "Supply Chain / Procurement Manager",
        "finance_risk_investment": "Finance / Risk / Investment Manager",
        "data_technology_analytics": "Data / Technology / Analytics Specialist",
        "partnerships_certification": "Partnerships / Certification / Standards Specialist",
        "other": "Other:",
    },
    "individual": {
        "other": "Other:",
    },
    "other": {
        "other": "Other:",
    },
}
