"""Country codes and names for user profiles."""

# ISO 3166-1 alpha-2 country codes with display names (alphabetical by country name)
COUNTRIES = {
    "AF": "Afghanistan",
    "AR": "Argentina",
    "AU": "Australia",
    "AT": "Austria",
    "BD": "Bangladesh",
    "BE": "Belgium",
    "BZ": "Belize",
    "BR": "Brazil",
    "BF": "Burkina Faso",
    "KH": "Cambodia",
    "CM": "Cameroon",
    "CA": "Canada",
    "CF": "Central African Republic",
    "TD": "Chad",
    "CL": "Chile",
    "CN": "China",
    "CO": "Colombia",
    "CG": "Congo",
    "CR": "Costa Rica",
    "CI": "Côte d'Ivoire",
    "CZ": "Czech Republic",
    "CD": "Democratic Republic of Congo",
    "DK": "Denmark",
    "EG": "Egypt",
    "SV": "El Salvador",
    "ET": "Ethiopia",
    "FJ": "Fiji",
    "FI": "Finland",
    "FR": "France",
    "GA": "Gabon",
    "GM": "Gambia",
    "DE": "Germany",
    "GH": "Ghana",
    "GR": "Greece",
    "GT": "Guatemala",
    "GN": "Guinea",
    "HN": "Honduras",
    "HK": "Hong Kong",
    "HU": "Hungary",
    "IN": "India",
    "ID": "Indonesia",
    "IR": "Iran",
    "IQ": "Iraq",
    "IE": "Ireland",
    "IL": "Israel",
    "IT": "Italy",
    "JP": "Japan",
    "KZ": "Kazakhstan",
    "KE": "Kenya",
    "KR": "South Korea",
    "KG": "Kyrgyzstan",
    "LA": "Laos",
    "LR": "Liberia",
    "MY": "Malaysia",
    "ML": "Mali",
    "MR": "Mauritania",
    "MX": "Mexico",
    "MN": "Mongolia",
    "MA": "Morocco",
    "MM": "Myanmar",
    "NL": "Netherlands",
    "NC": "New Caledonia",
    "NZ": "New Zealand",
    "NI": "Nicaragua",
    "NE": "Niger",
    "NG": "Nigeria",
    "NO": "Norway",
    "PK": "Pakistan",
    "PA": "Panama",
    "PG": "Papua New Guinea",
    "PE": "Peru",
    "PH": "Philippines",
    "PL": "Poland",
    "PT": "Portugal",
    "RU": "Russia",
    "RW": "Rwanda",
    "SA": "Saudi Arabia",
    "SN": "Senegal",
    "SL": "Sierra Leone",
    "SG": "Singapore",
    "SB": "Solomon Islands",
    "ZA": "South Africa",
    "ES": "Spain",
    "LK": "Sri Lanka",
    "SE": "Sweden",
    "CH": "Switzerland",
    "TW": "Taiwan",
    "TJ": "Tajikistan",
    "TZ": "Tanzania",
    "TH": "Thailand",
    "TR": "Turkey",
    "TM": "Turkmenistan",
    "UG": "Uganda",
    "UA": "Ukraine",
    "AE": "United Arab Emirates",
    "GB": "United Kingdom",
    "US": "United States",
    "UZ": "Uzbekistan",
    "VU": "Vanuatu",
    "VN": "Vietnam",
    "OTHER": "Other"
}