import uuid

import pytest

from src.tools.generate_insights import generate_insights

update = {
    "aoi": {
        "source": "gadm",
        "src_id": "USA.3.11",
        "name": "Pima, Arizona, United States",
        "subtype": "district-county",
        "gadm_id": "USA.3.11_1",
    },
    "subregion_aois": None,
    "subregion": None,
    "aoi_name": "Pima, Arizona, United States",
    "subtype": "district-county",
    "dataset": {
        "dataset_id": 4,
        "context_layer": None,
        "date_request_match": True,
        "reason": "The Tree cover loss dataset is specifically designed to map annual global forest loss and monitor deforestation trends from 2001 to 2024, making it the perfect match for analyzing tree cover loss trends over time.",
        "tile_url": "https://tiles.globalforestwatch.org/umd_tree_cover_loss/latest/dynamic/{z}/{x}/{y}.png?start_year=2001&end_year=2024&tree_cover_density_threshold=25&render_type=true_color",
        "dataset_name": "Tree cover loss",
        "analytics_api_endpoint": "/v0/land_change/tree_cover_loss/analytics",
        "description": "Tree Cover Loss (Hansen/UMD/GLAD) maps annual global forest loss from 2001 to 2024 at 30",
        "prompt_instructions": "Reports gross annual loss of tree cover ≥ 5 m height (2001-2024). Show yearly ",
        "methodology": "This data set, a collaboration between the GLAD (Global Land Analysis & Discovery) lab",
        "cautions": 'In this data set, "tree cover" is defined as all vegetation greater than 5 meters in height',
        "function_usage_notes": "Identifies areas of gross tree cover loss\n",
        "citation": 'Hansen et al., 2013. "High-Resolution Global Maps of 21st-Century Forest Cover Change." Accessed through Global Forest Watch on [date]. www.globalforestwatch.org\n',
    },
    "is_last_step": False,
    "remaining_steps": 20,
    "raw_data": {
        "Pima, Arizona, United States": {
            "country": [
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
                "USA",
            ],
            "region": [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
            "subregion": [
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
            ],
            "alert_date": [
                "2024-07-02",
                "2024-07-03",
                "2024-07-05",
                "2024-07-07",
                "2024-07-10",
                "2024-07-11",
                "2024-07-12",
                "2024-07-15",
                "2024-07-17",
                "2024-07-19",
                "2024-07-20",
                "2024-07-22",
                "2024-07-25",
                "2024-07-26",
                "2024-07-27",
                "2024-07-30",
            ],
            "confidence": [
                "high",
                "high",
                "high",
                "high",
                "high",
                "high",
                "high",
                "high",
                "high",
                "high",
                "high",
                "high",
                "high",
                "high",
                "high",
                "high",
            ],
            "value": [
                133035.84375,
                98698.4765625,
                7198.0087890625,
                427562.96875,
                6532.4423828125,
                427380.8125,
                177973.953125,
                10469.333984375,
                842927.125,
                325423.5,
                4577.6240234375,
                94053.0234375,
                146477.453125,
                439116.15625,
                683501.1875,
                142804.90625,
            ],
            "aoi_id": [
                "USA.3.11",
                "USA.3.11",
                "USA.3.11",
                "USA.3.11",
                "USA.3.11",
                "USA.3.11",
                "USA.3.11",
                "USA.3.11",
                "USA.3.11",
                "USA.3.11",
                "USA.3.11",
                "USA.3.11",
                "USA.3.11",
                "USA.3.11",
                "USA.3.11",
                "USA.3.11",
            ],
            "aoi_type": [
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
            ],
        },
        "Bern, Switzerland": {
            "country": [
                "CHE",
                "CHE",
                "CHE",
                "CHE",
                "CHE",
                "CHE",
                "CHE",
                "CHE",
                "CHE",
                "CHE",
                "CHE",
                "CHE",
                "CHE",
                "CHE",
                "CHE",
                "CHE",
            ],
            "region": [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
            "subregion": [
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
            ],
            "alert_date": [
                "2024-07-02",
                "2024-07-03",
                "2024-07-05",
                "2024-07-07",
                "2024-07-10",
                "2024-07-11",
                "2024-07-12",
                "2024-07-15",
                "2024-07-17",
                "2024-07-19",
                "2024-07-20",
                "2024-07-22",
                "2024-07-25",
                "2024-07-26",
                "2024-07-27",
                "2024-07-30",
            ],
            "confidence": [
                "high",
                "high",
                "high",
                "high",
                "high",
                "high",
                "high",
                "high",
                "high",
                "high",
                "high",
                "high",
                "high",
                "high",
                "high",
                "high",
            ],
            "value": [
                13335.84375,
                9898.4765625,
                798.0087890625,
                42562.96875,
                652.4423828125,
                42380.8125,
                17973.953125,
                1049.333984375,
                84927.125,
                32423.5,
                477.6240234375,
                9453.0234375,
                14647.453125,
                43916.15625,
                68501.1875,
                14804.90625,
            ],
            "aoi_id": [
                "CHE.2.12",
                "CHE.2.12",
                "CHE.2.12",
                "CHE.2.12",
                "CHE.2.12",
                "CHE.2.12",
                "CHE.2.12",
                "CHE.2.12",
                "CHE.2.12",
                "CHE.2.12",
                "CHE.2.12",
                "CHE.2.12",
                "CHE.2.12",
                "CHE.2.12",
                "CHE.2.12",
                "CHE.2.12",
            ],
            "aoi_type": [
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
                "admin",
            ],
        },
    },
}


# Override database fixtures to avoid database connections for these unit tests
@pytest.fixture(scope="function", autouse=True)
def test_db():
    """Override the global test_db fixture to avoid database connections."""
    pass


@pytest.fixture(scope="function", autouse=True)
def test_db_session():
    """Override the global test_db_session fixture to avoid database connections."""
    pass


@pytest.mark.asyncio
async def test_pick_aoi_queries():
    command = await generate_insights.ainvoke(
        {
            "query": "Compare tree cover loss in Pima County, Arizona with Bern, Switzerland",
            "is_comparison": True,
            "tool_call_id": str(uuid.uuid4()),
            "state": update,
        }
    )

    assert "charts_data" in command.update
    assert "Pima_Arizona" in command.update["charts_data"][0]["data"][0]
    assert "Bern_Switzerland" in command.update["charts_data"][0]["data"][0]
