"""Resolve a country-specific administrative term to its GADM depth (ADM1-5).

The same English word names a different depth in different countries -- e.g.
Spain's "provinces" (Sevilla, Almeria, ...) are GADM's ADM2, while Canada's
"provinces" are ADM1. A single global word-to-depth table cannot be correct
for both, so this module resolves per country instead, against the fixture
generated by ``scripts/generate_gadm_admin_types.py`` from GADM's own
``ENGTYPE_N`` columns.

``GADM_ADMIN_TERMS`` is the curated, enum-constrained vocabulary the geocoder
LLM extracts from the user's request (never freeform, so it can't drift from
GADM's real terminology or carry a typo). ``resolve_gadm_admin_level`` then
maps ``(term, iso3)`` to the correct depth, falling back to the closest term
actually present for that country when the exact word doesn't apply there.
"""

import difflib
import json
from enum import StrEnum
from pathlib import Path
from typing import Optional

_FIXTURE_PATH = Path(__file__).parent / "fixtures" / "gadm_admin_types.json"
_FIXTURE = json.loads(_FIXTURE_PATH.read_text())

# The vocabulary the geocoder LLM is constrained to via structured output.
# Curated from GADM's ENGTYPE_N columns: terms used by 2+ countries, plus a
# short allowlist of single-country terms that are still the natural word a
# user would use (the UK's "constituent countries", the UAE's "emirates").
GADM_ADMIN_TERMS: list[str] = _FIXTURE["canonical_terms"]

# Built dynamically from the fixture, so mypy can't enumerate its members.
GadmAdminTerm = StrEnum(  # type: ignore[misc]
    "GadmAdminTerm",
    {
        t.upper().replace(" ", "_").replace("-", "_"): t
        for t in GADM_ADMIN_TERMS
    },
)

# {iso3: {level (as str "1".."5"): [ENGTYPE values GADM uses at that level]}}
# Broader than GADM_ADMIN_TERMS on purpose: it also carries the long tail of
# country-specific/misspelled ENGTYPE values, used only as fuzzy-match targets
# below, never shown to the LLM.
_BY_COUNTRY: dict = _FIXTURE["by_country"]

# High on purpose: at 0.6 this matched unrelated words that happen to share
# letters (e.g. "City" -> "County", "Community" -> "Commune"), which is worse
# than doing nothing since a bad fuzzy hit silently overrides the LLM's
# global default. 0.85 still catches genuine near-misses/typos (GADM's own
# "Sate" for "State") while rejecting those semantic mismatches.
_FUZZY_CUTOFF = 0.85


def resolve_gadm_admin_level(term: str, iso3: str) -> Optional[int]:
    """Resolve *term* (e.g. "provinces") to the GADM depth (1-5) it names in *iso3*.

    Tries an exact case-insensitive match first, preferring the shallowest
    level when a term is used at more than one depth in that country (e.g.
    China's ENGTYPE "Municipality" appears at both ADM1 -- Beijing, Shanghai
    -- and ADM2/3; the ADM1 sense is what "municipalities of China" means).
    Falls back to the closest term GADM actually uses for that country, so an
    LLM choice that's valid somewhere else but wrong for this country (or a
    near-miss against GADM's own typos) still resolves. Returns ``None`` when
    the country is unknown or nothing matches closely enough; the caller
    should fall back to the generic depth default in that case.
    """
    country = _BY_COUNTRY.get(iso3.upper())
    if not country:
        return None

    term_lower = term.strip().lower()
    for level in sorted(country, key=int):
        if any(t.lower() == term_lower for t in country[level]):
            return int(level)

    all_terms = [t for terms in country.values() for t in terms]
    match = difflib.get_close_matches(
        term, all_terms, n=1, cutoff=_FUZZY_CUTOFF
    )
    if not match:
        return None
    matched = match[0]
    for level in sorted(country, key=int):
        if matched in country[level]:
            return int(level)
    return None
