"""Record production AOI candidate frames for the PZB-1392 designation cohort.

The local dev database holds GADM only, so the protected-area rows this bug is
about cannot be reproduced offline. This script records what production
retrieval actually returns for each search term of the ``aoi/designations``
CHALLENGE cohort, so the scorer can be regression-tested against real frames in
a plain unit test -- no database, no LLM, no network at test time.

Fidelity note: the geocoder narrows its search to one source when the extracted
place carries an ``area_type`` (``_resolve_place`` in
``src/agent/subagents/pick_aoi/tool.py``), and only retries every source when
the narrowed frame comes back empty. Every frame here is therefore recorded
against the source that case's designation implies -- ``wdpa`` for a park or
reserve, ``landmark`` for an Indigenous territory. They are NOT what
``GET /api/aois`` shows a frontend caller with no source filter, and the
metadata block in the output says so.

The two terms per prompt are hand-written to the rules in
``src/agent/subagents/pick_aoi/prompts.py`` (``place`` keeps the designation and
is de-accented English; ``canonical`` drops the designation and restores the
official spelling). They are deliberately NOT generated by calling the model:
the fixture has to be deterministic, and the extraction step is not what this
bug is about.

Usage::

    API_TOKEN=... uv run python scripts/record_designation_candidates.py

Writes ``tests/fixtures/aoi_designation_candidates_v1.json``.
"""

import json
import os
import sys
import urllib.parse
import urllib.request
from datetime import UTC, datetime
from pathlib import Path

API_BASE = "https://api.globalnaturewatch.org"
ENDPOINT = "/api/aois"
# The source a case's search is narrowed to, which is the source the geocoder
# infers from the designation the user used. Most of the cohort names a
# protected area; the Indigenous-territory cases resolve against `landmark`.
DEFAULT_SOURCE = "wdpa"
LIMIT = 10

OUTPUT = (
    Path(__file__).resolve().parents[1]
    / "tests"
    / "fixtures"
    / "aoi_designation_candidates_v1.json"
)

# One entry per CHALLENGE case in gnw-gold-evals cases/challenge/aoi/designations.
# `terms` is [place, canonical], in the order `_resolve_place` builds them.
CASES = [
    {
        "case_id": "ch-aoi-132",
        "query": "Show me Sankuru National Reserve",
        "terms": ["Sankuru National Reserve", "Sankuru"],
        "expected_src_id": "354001",
    },
    {
        "case_id": "ch-aoi-133",
        "query": "Go to Yaguas National Park",
        "terms": ["Yaguas National Park", "Yaguas"],
        "expected_src_id": "555629239",
    },
    {
        "case_id": "ch-aoi-134",
        "query": "Show me the Okapi Wildlife Reserve",
        "terms": ["Okapi Wildlife Reserve", "Okapi"],
        "expected_src_id": "37043",
    },
    {
        "case_id": "ch-aoi-135",
        "query": "Zoom to Ivindo National Park",
        "terms": ["Ivindo National Park", "Ivindo"],
        "expected_src_id": "303873",
    },
    {
        "case_id": "ch-aoi-136",
        "query": "Show me Rio Pure National Park",
        "terms": ["Rio Pure National Park", "Río Puré"],
        "expected_src_id": "303547",
    },
    {
        "case_id": "ch-aoi-137",
        "query": "Go to Virunga National Park",
        "terms": ["Virunga National Park", "Virunga"],
        "expected_src_id": "166889",
    },
    {
        "case_id": "ch-aoi-138",
        "query": "Show me Salonga National Park",
        "terms": ["Salonga National Park", "Salonga"],
        "expected_src_id": "555697863",
    },
    {
        "case_id": "ch-aoi-139",
        "query": "Zoom to Kahuzi-Biega National Park",
        "terms": ["Kahuzi-Biega National Park", "Kahuzi-Biega"],
        "expected_src_id": "1082",
    },
    {
        "case_id": "ch-aoi-140",
        "query": "Show me Lope National Park in Gabon",
        "terms": ["Lope National Park, Gabon", "Lopé, Gabon"],
        "expected_src_id": "303875",
    },
    {
        "case_id": "ch-aoi-141",
        "query": "Go to Odzala-Kokoua National Park",
        "terms": ["Odzala-Kokoua National Park", "Odzala-Kokoua"],
        "expected_src_id": "643",
    },
    {
        "case_id": "ch-aoi-142",
        "query": "Show me Madidi National Park",
        "terms": ["Madidi National Park", "Madidi"],
        "expected_src_id": "98183",
    },
    {
        "case_id": "ch-aoi-143",
        "query": "Zoom to Yasuni National Park",
        "terms": ["Yasuni National Park", "Yasuní"],
        "expected_src_id": "186",
    },
    {
        "case_id": "ch-aoi-144",
        "query": "Show me Cordillera Azul National Park",
        "terms": ["Cordillera Azul National Park", "Cordillera Azul"],
        "expected_src_id": "303320",
    },
    {
        "case_id": "ch-aoi-145",
        "query": "Go to Corcovado National Park in Costa Rica",
        "terms": [
            "Corcovado National Park, Costa Rica",
            "Corcovado, Costa Rica",
        ],
        "expected_src_id": "164",
    },
    {
        "case_id": "ch-aoi-146",
        "query": "Show me Chiribiquete National Park",
        "terms": ["Chiribiquete National Park", "Chiribiquete"],
        "expected_src_id": "19984",
    },
    {
        "case_id": "ch-aoi-147",
        "query": "Show me Hin Nam No National Park",
        "terms": ["Hin Nam No National Park", "Hin Nam No"],
        "expected_src_id": "555703744",
    },
    {
        # The native phrasing translates to the same English `place` as
        # ch-aoi-134; only `canonical` differs ("Okapis", not "Okapi").
        "case_id": "ch-aoi-149",
        "query": "Show me the Réserve de faune à Okapis",
        "terms": ["Okapi Wildlife Reserve", "Okapis"],
        "expected_src_id": "37043",
    },
    {
        "case_id": "ch-aoi-150",
        "query": "Zoom to Parc National de l'Ivindo",
        "terms": ["Ivindo National Park", "Ivindo"],
        "expected_src_id": "303873",
    },
    {
        "case_id": "ch-aoi-151",
        "query": "Show me the Matsés Native Community in Peru",
        "terms": ["Matses Native Community, Peru", "Matsés, Peru"],
        "source": "landmark",
        "expected_src_id": "PER1700",
    },
    {
        # WDPA 34004 "Kayapó, Terra Indígena, BRA" is a defensible alternative
        # but is not what the cohort expects; the landmark row is.
        "case_id": "ch-aoi-152",
        "query": "Go to the Kayapó Indigenous Territory",
        "terms": ["Kayapo Indigenous Territory", "Kayapó"],
        "source": "landmark",
        "expected_src_id": "BRA1507",
    },
    {
        # The designation is already inside the stored leaf ("Sapo National
        # Park, National Park, LBR"), so the leaf is not a bare place name.
        "case_id": "ch-aoi-153",
        "query": "Show me Sapo National Park",
        "terms": ["Sapo National Park", "Sapo"],
        "expected_src_id": "7409",
    },
    {
        # Near-miss 10801 "Parque do Tumucumaque, Terra Indígena, BRA".
        "case_id": "ch-aoi-154",
        "query": "Zoom to Tumucumaque Mountains National Park",
        "terms": [
            "Tumucumaque Mountains National Park",
            "Montanhas do Tumucumaque",
        ],
        "expected_src_id": "351784",
    },
]


def fetch_frame(term: str, source: str, token: str) -> list[dict]:
    """The rows production returns for one search term, in rank order."""
    query = urllib.parse.urlencode(
        {"name": term, "source": source, "limit": LIMIT}
    )
    request = urllib.request.Request(
        f"{API_BASE}{ENDPOINT}?{query}",
        headers={"Authorization": f"Bearer {token}"},
    )
    with urllib.request.urlopen(request, timeout=60) as response:
        if response.status != 200:
            raise RuntimeError(f"{term!r}: HTTP {response.status}")
        return json.loads(response.read())


def main() -> int:
    token = os.environ.get("API_TOKEN")
    if not token:
        print("API_TOKEN is required", file=sys.stderr)
        return 1

    wanted = sorted(
        {
            (case.get("source", DEFAULT_SOURCE), term)
            for case in CASES
            for term in case["terms"]
        }
    )
    # Keyed by source then term: the same term can be searched against two
    # sources, and the frames are not interchangeable.
    frames: dict[str, dict[str, list[dict]]] = {}
    for source, term in wanted:
        rows = fetch_frame(term, source, token)
        frames.setdefault(source, {})[term] = rows
        print(f"{source} {term!r}: {len(rows)} row(s)", file=sys.stderr)

    OUTPUT.write_text(
        json.dumps(
            {
                "metadata": {
                    "recorded_at": datetime.now(UTC).strftime("%Y-%m-%d"),
                    "api_base": API_BASE,
                    "endpoint": ENDPOINT,
                    "default_source_filter": DEFAULT_SOURCE,
                    "limit": LIMIT,
                    "note": (
                        "Source-narrowed frames, matching what the geocoder "
                        "searches for a place carrying an area_type (see each "
                        "case's `source`). NOT the unfiltered GET /api/aois "
                        "view a frontend caller sees."
                    ),
                    "cohort": (
                        "gnw-gold-evals cases/challenge/aoi/designations"
                    ),
                },
                "cases": CASES,
                "frames": frames,
            },
            indent=2,
            ensure_ascii=False,
            sort_keys=False,
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"wrote {OUTPUT} ({OUTPUT.stat().st_size} bytes)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
